<?php

/**
 * Regenerate resources/aws/api-gateway-ranges.php from AWS's published IP ranges.
 *
 * Usage: php scripts/refresh-aws-api-gateway-ranges.php [path-or-url-to-ip-ranges.json]
 *
 * The output is committed, so the middleware never fetches anything at runtime. A range
 * AWS adds after the last refresh is simply not trusted, which leaves the gateway's own
 * address as the client IP for those requests rather than trusting a client-supplied one.
 */
$source = $argv[1] ?? 'https://ip-ranges.amazonaws.com/ip-ranges.json';
$target = __DIR__.'/../resources/aws/api-gateway-ranges.php';

$raw = file_get_contents($source);
if ($raw === false) {
    fwrite(STDERR, "Could not read {$source}\n");
    exit(1);
}

$data = json_decode($raw, true);
if (! is_array($data) || ! isset($data['createDate'], $data['prefixes'], $data['ipv6_prefixes'])) {
    fwrite(STDERR, "{$source} is not an AWS ip-ranges document\n");
    exit(1);
}

$regions = [];
foreach ($data['prefixes'] as $prefix) {
    if ($prefix['service'] === 'API_GATEWAY') {
        $regions[$prefix['region']][] = $prefix['ip_prefix'];
    }
}
foreach ($data['ipv6_prefixes'] as $prefix) {
    if ($prefix['service'] === 'API_GATEWAY') {
        $regions[$prefix['region']][] = $prefix['ipv6_prefix'];
    }
}

if ($regions === []) {
    fwrite(STDERR, "No API_GATEWAY prefixes found in {$source}\n");
    exit(1);
}

ksort($regions);
foreach ($regions as &$cidrs) {
    $cidrs = array_values(array_unique($cidrs));
    sort($cidrs);
}
unset($cidrs);

$out = "<?php\n\n";
$out .= "// Generated by scripts/refresh-aws-api-gateway-ranges.php. Do not edit by hand.\n";
$out .= '// Source: AWS ip-ranges.json, service API_GATEWAY, createDate '.$data['createDate'].".\n\n";
$out .= "return [\n";
$out .= "    'create_date' => ".var_export($data['createDate'], true).",\n";
$out .= "    'regions' => [\n";
foreach ($regions as $region => $cidrs) {
    $out .= '        '.var_export($region, true)." => [\n";
    foreach ($cidrs as $cidr) {
        $out .= '            '.var_export($cidr, true).",\n";
    }
    $out .= "        ],\n";
}
$out .= "    ],\n";
$out .= "];\n";

if (! is_dir(dirname($target))) {
    mkdir(dirname($target), 0755, true);
}
file_put_contents($target, $out);

$count = array_sum(array_map('count', $regions));
echo "Wrote {$count} prefixes across ".count($regions)." regions (createDate {$data['createDate']}) to resources/aws/api-gateway-ranges.php\n";
