<?php

namespace NuiMarkets\LaravelSharedUtils\Http\Middleware;

use Illuminate\Http\Middleware\TrustProxies;
use Illuminate\Http\Request;
use Illuminate\Support\Env;
use Symfony\Component\HttpFoundation\IpUtils;

/**
 * Trusted-proxy middleware for services reached through AWS API Gateway and a load balancer.
 *
 * With `$proxies = '*'`, Laravel trusts only the immediate caller (the load balancer), so for
 * a request routed client -> API Gateway -> load balancer, `$request->ip()` resolves to the
 * API Gateway's egress address. This middleware also trusts that one gateway hop, so the next
 * entry to the left, the address API Gateway itself appended, is returned instead. Requests
 * that reach the load balancer directly are unaffected.
 *
 * Exactly one hop is trusted, and only when its address is in the region's published
 * API_GATEWAY ranges: walking X-Forwarded-For from the right past the immediate caller and
 * `$additionalProxies`, the first entry is trusted if it is a gateway address, and nothing to
 * its left is. Symfony trusts by address rather than position, so the hop is trusted only
 * when the entry to its left, the caller API Gateway appended, is a valid address other than
 * the hop and the immediate caller; otherwise the gateway address is returned. Trusting the ranges wholesale would let a caller whose own address is in those
 * ranges have Symfony fall back to the leftmost entry, which the client chooses.
 *
 * Entries a client puts in X-Forwarded-For sit to the left of the address API Gateway
 * appends, so they are never returned. Values that are not IP addresses are dropped by
 * Symfony's client-IP resolution.
 *
 * Anyone able to run their own API Gateway in the same region can still choose the forwarded
 * address, because its egress is a gateway address too. Use the resolved IP for logging,
 * attribution and throttling, and enforce IP allow-lists at the gateway on the source IP it
 * records.
 *
 * The ranges come from resources/aws/api-gateway-ranges.php, regenerated by
 * scripts/refresh-aws-api-gateway-ranges.php. A range AWS adds after the last refresh is not
 * trusted, which falls back to the gateway address rather than a client-supplied one.
 *
 * Requires the load balancer to append to X-Forwarded-For (ALB `append` mode, the default;
 * under `preserve`, traffic reaching the load balancer directly carries a client-written
 * rightmost entry) and application ingress restricted to that load balancer, since the
 * immediate caller is always trusted. See docs/trusted-proxies.md.
 *
 * Usage: register it (or a subclass) as the first global middleware in place of the
 * framework's TrustProxies, and set `$region` when the runtime does not export AWS_REGION.
 * The static `TrustProxies::at()` override, a `$proxies` property and `trustedproxy.proxies`
 * config are all ignored here; list extra proxies in `$additionalProxies`.
 */
class TrustAwsApiGatewayProxies extends TrustProxies
{
    /**
     * AWS region whose API Gateway ranges are trusted. Null reads AWS_REGION, then
     * AWS_DEFAULT_REGION from the environment.
     */
    protected ?string $region = null;

    /**
     * Further proxies to trust (IPs or CIDRs), on top of the immediate caller and the
     * API Gateway hop.
     *
     * @var array<int, string>
     */
    protected array $additionalProxies = [];

    /** @var array{create_date: string, regions: array<string, array<int, string>>}|null */
    private static ?array $ranges = null;

    /**
     * Trust the immediate caller, any additional proxies, and the single API Gateway hop.
     *
     * The caller's address is read from the request itself rather than passed to Symfony as
     * the 'REMOTE_ADDR' token, which some framework versions resolve from the global $_SERVER.
     *
     * @return void
     */
    protected function setTrustedProxyIpAddresses(Request $request)
    {
        $trusted = array_values(array_filter(array_merge(
            [$request->server->get('REMOTE_ADDR')],
            $this->additionalProxies,
        ), fn ($proxy) => is_string($proxy) && $proxy !== ''));

        $gatewayHop = $this->gatewayHop($request, $trusted);
        if ($gatewayHop !== null) {
            $trusted[] = $gatewayHop;
        }

        $request->setTrustedProxies($trusted, $this->getTrustedHeaderNames());
    }

    /**
     * The X-Forwarded-For entry the load balancer appended for an API Gateway caller, or null
     * when that entry is not in the region's gateway ranges.
     *
     * @param  array<int, string>  $trusted
     */
    protected function gatewayHop(Request $request, array $trusted): ?string
    {
        if (($this->getTrustedHeaderNames() & Request::HEADER_X_FORWARDED_FOR) === 0) {
            return null;
        }

        $ranges = static::apiGatewayRanges($this->resolveRegion());
        if ($ranges === [] || $trusted === []) {
            return null;
        }

        $entries = explode(',', (string) $request->headers->get('X-Forwarded-For', ''));
        for ($i = count($entries) - 1; $i >= 0; $i--) {
            $ip = static::normaliseForwardedIp($entries[$i]);
            if ($ip === null) {
                return null;
            }
            if (IpUtils::checkIp($ip, $trusted)) {
                continue;
            }
            if (! IpUtils::checkIp($ip, $ranges)) {
                return null;
            }

            // Symfony trusts by address, not position, so a caller API Gateway appended that
            // equals this hop or the immediate caller would be skipped too, exposing an entry
            // the client wrote; a non-IP caller would be dropped, with the same effect. Keep
            // the gateway address instead. A caller in $additionalProxies is a proxy the
            // application chose to trust, so continuing past it is the intended behaviour.
            $caller = $i > 0 ? static::normaliseForwardedIp($entries[$i - 1]) : null;
            $remote = $request->server->get('REMOTE_ADDR');
            if ($caller === null || IpUtils::checkIp($caller, $ip) || (is_string($remote) && IpUtils::checkIp($caller, $remote))) {
                return null;
            }

            return $ip;
        }

        return null;
    }

    /**
     * An X-Forwarded-For entry as an IP address, with brackets and any port stripped the way
     * Symfony strips them, or null when it is not an IP address.
     */
    protected static function normaliseForwardedIp(string $entry): ?string
    {
        $entry = trim($entry);
        if (str_starts_with($entry, '[')) {
            $end = strpos($entry, ']', 1);
            $entry = $end === false ? '' : substr($entry, 1, $end - 1);
        } elseif (strpos($entry, '.') && substr_count($entry, ':') === 1) {
            $entry = (string) strstr($entry, ':', true);
        }

        return filter_var($entry, FILTER_VALIDATE_IP) === false ? null : $entry;
    }

    /**
     * Published API_GATEWAY CIDRs for a region, empty for an unknown or null region.
     *
     * @return array<int, string>
     */
    public static function apiGatewayRanges(?string $region): array
    {
        if ($region === null || $region === '') {
            return [];
        }

        self::$ranges ??= require __DIR__.'/../../../resources/aws/api-gateway-ranges.php';

        return self::$ranges['regions'][$region] ?? [];
    }

    protected function resolveRegion(): ?string
    {
        return $this->region
            ?? (Env::get('AWS_REGION') ?: null)
            ?? (Env::get('AWS_DEFAULT_REGION') ?: null);
    }
}
