<?php

namespace NuiMarkets\LaravelSharedUtils\Http\Middleware;

use Illuminate\Http\Middleware\TrustProxies;
use Illuminate\Http\Request;
use Illuminate\Support\Env;

/**
 * Trusted-proxy middleware for services reached through AWS API Gateway and a load balancer.
 *
 * With `$proxies = '*'`, Laravel trusts only the immediate caller (the load balancer), so for
 * a request routed client -> API Gateway -> load balancer, `$request->ip()` resolves to the
 * API Gateway's egress address. This middleware also trusts the published API_GATEWAY ranges
 * for one region, so the next hop to the left, the address API Gateway itself appended, is
 * returned instead. Requests that reach the load balancer directly are unaffected.
 *
 * Entries a client puts in X-Forwarded-For sit to the left of the address API Gateway
 * appends, so they are never returned. Values that are not IP addresses are dropped by
 * Symfony's client-IP resolution.
 *
 * Anyone able to run their own API Gateway in the same region can still choose the forwarded
 * address, because its egress is trusted too. Use the resolved IP for logging, attribution
 * and throttling, and enforce IP allow-lists at the gateway on the source IP it records.
 *
 * The ranges come from resources/aws/api-gateway-ranges.php, regenerated by
 * scripts/refresh-aws-api-gateway-ranges.php. A range AWS adds after the last refresh is not
 * trusted, which falls back to the gateway address rather than a client-supplied one.
 *
 * Usage: register it (or a subclass) as the first global middleware in place of the
 * framework's TrustProxies, and set `$region` when the runtime does not export AWS_REGION.
 * The static `TrustProxies::at()` override is deliberately ignored here.
 */
class TrustAwsApiGatewayProxies extends TrustProxies
{
    /**
     * AWS region whose API Gateway ranges are trusted. Null reads AWS_REGION, then
     * AWS_DEFAULT_REGION from the environment.
     */
    protected ?string $region = null;

    /**
     * Further proxies to trust (IPs or CIDRs), on top of the immediate caller and the
     * API Gateway ranges.
     *
     * @var array<int, string>
     */
    protected array $additionalProxies = [];

    /**
     * The headers that should be used to detect proxies.
     *
     * @var int
     */
    protected $headers =
        Request::HEADER_X_FORWARDED_FOR |
        Request::HEADER_X_FORWARDED_HOST |
        Request::HEADER_X_FORWARDED_PORT |
        Request::HEADER_X_FORWARDED_PROTO |
        Request::HEADER_X_FORWARDED_AWS_ELB;

    /** @var array{create_date: string, regions: array<string, array<int, string>>}|null */
    private static ?array $ranges = null;

    /**
     * The immediate caller, the region's API Gateway ranges, and any additional proxies.
     *
     * @return array<int, string>
     */
    protected function proxies()
    {
        return array_values(array_merge(
            ['REMOTE_ADDR'],
            static::apiGatewayRanges($this->resolveRegion()),
            $this->additionalProxies,
        ));
    }

    /**
     * Published API_GATEWAY CIDRs for a region, empty for an unknown or null region.
     *
     * @return array<int, string>
     */
    public static function apiGatewayRanges(?string $region): array
    {
        if ($region === null || $region === '') {
            return [];
        }

        self::$ranges ??= require __DIR__.'/../../../resources/aws/api-gateway-ranges.php';

        return self::$ranges['regions'][$region] ?? [];
    }

    protected function resolveRegion(): ?string
    {
        return $this->region
            ?? (Env::get('AWS_REGION') ?: null)
            ?? (Env::get('AWS_DEFAULT_REGION') ?: null);
    }
}
